#!/bin/sh -ex

# Install NFS client dependencies.
apt-get install -y nfs-common

# Prepare the mount point.
mkdir -p /var/nfs-share

# Grab the IP of the NFS server container from Docker.
# (Required because for some reason using the Docker service name (i.e. 'nfs-server') as the domain name won't work.)
SERVER_IP=$(docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" nfs-server)

# Mount the NFS volume.
# FIXME: it seems like this volume is not persisted in the Agent once this script terminates, and we
# need to re-execute from outside of `ddev` to make the volume persist. (???)
mount -v -t nfs -o vers=4,port=2049 $SERVER_IP:/ /var/nfs-share
